// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using heitech.configXt;
using heitech.configXt.Interface;

#nullable disable

namespace heitech.configXt.Migrationen
{
    [DbContext(typeof(SqliteStore))]
    [Migration("20220526175743_AddKind")]
    partial class AddKind
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("heitech.configXt.SqliteStore+ConfigModelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<ConfigKind>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigModelEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
